[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
seeds = false
skip-lint = false
[programs.localnet]
twitter = "31utvwA13kZZaTWcDCcwT2S1H877uRfKGydvnaMFXy2J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
